### ISSUE TITLE
T, K Settings to Replicate Paper Results

### ISSUE THREAD

**Issue by griffbr** [zhangxin-xd/Dataset-Pruning-TDDS#2]
Hi Zhang,

Thanks for your help and prompt reply on previous issue.

What are the T (`trajectory_len`) and K (`window_size`) parameter settings that you used with `importance_evaluation.py` to generate the Strategy-E results in Table 1 of your paper?

As one example of my confusion, the paper states that "For CIFAR-100, the optimal (p, T , K ) setting is (0.3, 90, 10),...," which is consistent with the plots in Figure 4. However, the maximum performance for CIFAR-100 with this setting in Figure 4 (~77.4 Test Acc.) do not match the corresponding results in Table 1 (77.56). I am unable to match Figure 4 / Table 1 results for the other settings as well (see images below).

Apologies if I am missing something from the paper, but can you explain why the results from Figure 4 and Table 1 are different? Were different T, K settings used to generate the results in Table 1? Was there another setting that changed?

Any guidance or clarification is much appreciated.

![Screenshot 2024-07-08 at 3 37 25 PM](https://github.com/zhangxin-xd/Dataset-Pruning-TDDS/assets/26256043/1f80666b-20d7-4e8c-b26f-96ac773f6f3e)

![Screenshot 2024-07-08 at 3 37 25 PM](https://github.com/zhangxin-xd/Dataset-Pruning-TDDS/assets/26256043/4742e827-aaa7-4957-9546-55b50a72726c)

**Comment by zhangxin-xd** [comment]
Hi, thanks for noticing  that. The accuracy in Table 1 and Figure 4 differs because the hyperparameter grid search was conducted before integrating with other components (as mentioned in the ablation study). However, the T (trajectory length) and K (window size) parameter settings for Table 1 are consistent with those in Figure 4.

**Comment by griffbr** [comment]
Hi, thanks for your reply.

"The accuracy in Table 1 and Figure 4 differs because the hyperparameter grid search was conducted before integrating with other components (as mentioned in the ablation study)." 

So (if I am understanding this correctly) the Table 1 results include performance improvements from the `Gradient Magnitude vs Gradient` and `KL-based Loss Difference` ablations above the _T_, _K_ ablation in Figure 4. 

Please let me know if this is correct or if I am missing any other specific details from your paper. Thanks again!

**Comment by zhangxin-xd** [comment]
Yes, that’s right.

---- Replied Message ----
| From | Brent ***@***.***> |
| Date | 07/11/2024 21:24 |
| To | zhangxin-xd/Dataset-Pruning-TDDS ***@***.***> |
| Cc | zhangxin-xd ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [zhangxin-xd/Dataset-Pruning-TDDS] T, K Settings to Replicate Paper Results (Issue #2) |

Hi, thanks for your reply.

"The accuracy in Table 1 and Figure 4 differs because the hyperparameter grid search was conducted before integrating with other components (as mentioned in the ablation study)."

So (if I am understanding this correctly) the Table 1 results include performance improvements from the Gradient Magnitude vs Gradient and KL-based Loss Difference ablations above the T, K ablation in Figure 4.

Please let me know if this is correct or if I am missing any other specific details from your paper. Thanks again!
